---
title: "discuss"
format: html
editor: source
---

```{r}
library(tidyverse)
library(sf)
library(terra)
library(stars)
library(gstat)
library(tmap)
library(kableExtra)
```
```{r}
ca_ecoregions <- st_read(here::here("data", "CA_Level3_Ecoregions_EPA", "ca_eco_l3.shp"))

bioclim_dir <- here::here("data", "wc2.1_2.5m")
bioclim <- list.files(bioclim_dir, pattern = glob2rx("*.tif$"), full.names = TRUE)
bioclim_sort <- bioclim[
  # Sort filepaths based on numeric suffix
  order(
  # Extract numeric suffix of filenames and convert to numeric
  as.numeric(gsub(".*_(\\d+)\\.tif$", "\\1", bioclim)))]
bioclim_rast <- rast(bioclim_sort)

variables <- c("annualMeanTemp", "meanDiurnalRange", "isothermality", "tempSeasonality", "maxTempWarmMonth", "maxTempColdMonth", "tempAnnualRange", "meanTempWetQ", "meanTempDryQ", "meanTempWarmQ", "meanTempColdQ", "annualPrecip", "precipWetMonth", "precipDryMonth", "precipSeasonality", "precipWetQ", "precipDryQ", "precipWarmQ", "precipColdQ")
names(bioclim_rast) <- variables
```

```{r}
ca_ecoregions <- st_transform(ca_ecoregions, crs(bioclim_rast))
```


```{r}
bioclim_crop <- terra::crop(bioclim_rast, ca_ecoregions)
bioclim_mask <- terra::mask(bioclim_crop, ca_ecoregions)

tm_shape(bioclim_mask) + 
  tm_raster()
```

```{r}
rand_points <- spatSample(bioclim_mask, 100, as.points = TRUE, na.rm = TRUE) %>% st_as_sf()
```


```{r}
stars_grid <- rand_points %>% sf::st_make_grid() %>% st_as_stars()
```

```{r}
annualMeanTemp_idw <- gstat::idw(annualMeanTemp ~ 1, locations = rand_points, newdata = stars_grid, idp = 2)
```

```{r}
idw_crop <- terra::crop(annualMeanTemp_idw, ca_ecoregions)
idw_mask <- terra::mask(annualMeanTemp_idw, ca_ecoregions)
```

```{r}
ca_ecoregions_rast <- rast(ca_ecoregions)
```

```{r}
tm_shape(annualMeanTemp_idw) +
  tm_raster()
```


```{r}
means <- zonal(idw_mask, ca_ecoregions_rast, fun = 'mean')
```

